### PR TITLE
fixing bug. Null value for temperatures should be ignored.

### LINKED ISSUE #393: [BUG] Invalid temp values in database
**Describe the bug**
The temp values showed for one of my HDD is wrong. They are below 25C and this is not possible.
I debugged a little and found that the data in influxdb has invalid temp values of 0C. That changes the calculated median and generates wrong calculated values.

**Expected behavior**
Correct temp values

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by AnalogJ**
fixes #393

### CODE REVIEW

File: webapp/backend/pkg/database/scrutiny_repository_temperature.go [hunk 1]
```diff
@@ -17,6 +17,10 @@ func (sr *scrutinyRepository) SaveSmartTemperature(ctx context.Context, wwn stri
 	if len(collectorSmartData.AtaSctTemperatureHistory.Table) > 0 {
 
 		for ndx, temp := range collectorSmartData.AtaSctTemperatureHistory.Table {
+			//temp value may be null, we must skip/ignore them. See #393
+			if temp == 0 {
```
Comment (adripo) [inline webapp/backend/pkg/database/scrutiny_repository_temperature.go:21]: I would suggest to use:
```
if temp != 0 {
    minutesOffset....
    ...
}
```

**Review by adripo — CHANGES_REQUESTED** [review]
